basePath: /api/v1
definitions:
  domain.CreateHotelRequest:
    properties:
      address:
        maxLength: 100
        type: string
      city:
        maxLength: 32
        type: string
      name:
        maxLength: 64
        type: string
      stars:
        maximum: 7
        minimum: 0
        type: integer
    required:
    - address
    - city
    - name
    - stars
    type: object
  domain.Hotel:
    properties:
      address:
        type: string
      city:
        type: string
      id:
        type: integer
      name:
        type: string
      stars:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Hotel microservice.
  title: Booking project
  version: "1.0"
paths:
  /hotels/{id}:
    get:
      consumes:
      - application/json
      description: Get hotel information by ID
      parameters:
      - description: Hotel ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Hotel'
      summary: Get hotel by ID
      tags:
      - Users
  /hotels/all:
    get:
      consumes:
      - application/json
      description: Get list of hotels
      parameters:
      - description: Hotel name
        in: query
        name: name
        type: string
      - description: City location
        in: query
        name: city
        type: string
      - description: Stars
        in: query
        name: stars
        type: integer
      - default: 5
        description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - default: 0
        description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Hotel'
            type: array
      summary: Get list of hotels
      tags:
      - Users
  /hotels/create:
    post:
      consumes:
      - application/json
      description: Add new hotel
      parameters:
      - description: Hotel data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateHotelRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Hotel'
      summary: Add new hotel
      tags:
      - Admin
  /hotels/update/{id}:
    put:
      consumes:
      - application/json
      description: Update hotel information
      parameters:
      - description: Hotel ID
        in: path
        name: id
        required: true
        type: integer
      - description: Hotel data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateHotelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update hotel information
      tags:
      - Admin
swagger: "2.0"
